version: '3.8'

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}" # IMPORTANT: Change this in .env file!
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # For Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  frontend:
    build: ./frontend
    container_name: gyouji-hp-frontend
    labels:
      - "traefik.enable=true"

      # 1. HTTP用のルーターを定義
      - "traefik.http.routers.frontend-http.rule=Host(`nitsche-gyouji.com`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"

      # 2. HTTPからHTTPSへリダイレクトするミドルウェアを定義・適用
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # 3. 既存のHTTPS用ルーター（名前をわかりやすく変更）
      - "traefik.http.routers.frontend-https.rule=Host(`nitsche-gyouji.com`)"
      - "traefik.http.routers.frontend-https.entrypoints=websecure"
      - "traefik.http.routers.frontend-https.tls.certresolver=myresolver"

      # サービス設定（変更なし）
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      # --- ↑ここまで追加・変更↑ ---
    networks:
      - web

networks:
  web:
    driver: bridge