# 本番環境用のdocker-compose設定
version: '3.8'

services:
  # 本番環境用MySQL設定
  mysql:
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_prod_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    # セキュリティ: 本番環境ではポートを公開しない
    ports: []
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 本番環境用バックエンド設定
  backend:
    restart: always
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_HOURS: ${JWT_EXPIRATION_HOURS}
      JWT_ISSUER: ${JWT_ISSUER}
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
      GIN_MODE: release
    # セキュリティ: 本番環境では直接ポートアクセスを無効化
    ports: []
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 本番環境用フロントエンド設定
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        NODE_ENV: production
    restart: always
    environment:
      NODE_ENV: production
      VITE_API_BASE_URL: /api
      VITE_APP_TITLE: Tournament Management System
      VITE_ENABLE_POLLING: "true"
      VITE_POLLING_INTERVAL: "30000"
      VITE_ENABLE_CSP: "true"
      VITE_ENABLE_HTTPS_REDIRECT: "true"
      VITE_LOG_LEVEL: warn
      VITE_ENABLE_ANALYTICS: "false"
      VITE_ENABLE_DEBUG: "false"
    # セキュリティ: 本番環境では直接ポートアクセスを無効化
    ports: []
    # 本番環境用セキュリティ強化
    security_opt:
      - no-new-privileges:true
      - apparmor:docker-default
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
      - /var/cache/nginx:noexec,nosuid,size=25m
      - /var/run:noexec,nosuid,size=5m
    # 本番環境用リソース制限
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
        compress: "true"

volumes:
  mysql_prod_data:
    driver: local