// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "管理者認証情報でログインし、JWTトークンを取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "ユーザーログイン",
                "parameters": [
                    {
                        "description": "ログイン情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ログイン成功",
                        "schema": {
                            "$ref": "#/definitions/handler.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "description": "ログアウト処理（JWTはステートレスのため、クライアント側でトークンを削除）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "ユーザーログアウト",
                "responses": {
                    "200": {
                        "description": "ログアウト成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "現在認証されているユーザーの情報を取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "ユーザープロフィール取得",
                "responses": {
                    "200": {
                        "description": "ユーザー情報",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/refresh": {
            "post": {
                "description": "既存のJWTトークンを使用して新しいトークンを生成する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "JWTトークンリフレッシュ",
                "parameters": [
                    {
                        "description": "リフレッシュ情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "リフレッシュ成功",
                        "schema": {
                            "$ref": "#/definitions/handler.RefreshTokenResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/validate": {
            "post": {
                "description": "JWTトークンの有効性を検証する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "トークン検証",
                "parameters": [
                    {
                        "description": "検証するトークン",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "検証成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/matches": {
            "get": {
                "description": "全ての試合を取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "全試合取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.MatchListResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しい試合を作成する（管理者のみ）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "試合作成",
                "parameters": [
                    {
                        "description": "試合作成情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "作成成功",
                        "schema": {
                            "$ref": "#/definitions/handler.MatchResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "競合エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/matches/id/{id}": {
            "get": {
                "description": "指定されたIDの試合を取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "ID別試合取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "試合ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.MatchResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/matches/tournament/{tournament_id}": {
            "get": {
                "description": "指定されたトーナメントの試合を取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "トーナメント別試合取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "トーナメントID",
                        "name": "tournament_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.MatchListResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/matches/tournament/{tournament_id}/next": {
            "get": {
                "description": "指定されたトーナメントの次に実施予定の試合を取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "次の試合取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "トーナメントID",
                        "name": "tournament_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.MatchListResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/matches/tournament/{tournament_id}/statistics": {
            "get": {
                "description": "指定されたトーナメントの試合統計を取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "試合統計取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "トーナメントID",
                        "name": "tournament_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.MatchStatisticsResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/matches/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDの試合を更新する（管理者のみ）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "試合更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "試合ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "試合更新情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/handler.MatchResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDの試合を削除する（管理者のみ）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "試合削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "試合ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "削除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "競合エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/matches/{id}/result": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定された試合の結果を提出する（管理者のみ）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "試合結果提出",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "試合ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "試合結果情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SubmitMatchResultRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "提出成功",
                        "schema": {
                            "$ref": "#/definitions/handler.MatchResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "ビジネスロジックエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/matches/{sport}": {
            "get": {
                "description": "指定されたスポーツの試合を取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "スポーツ別試合取得",
                "parameters": [
                    {
                        "enum": [
                            "volleyball",
                            "table_tennis",
                            "soccer"
                        ],
                        "type": "string",
                        "description": "スポーツ名",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.MatchListResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tournaments": {
            "get": {
                "description": "全てのトーナメントを取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "全トーナメント取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.TournamentListResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しいトーナメントを作成する（管理者のみ）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "トーナメント作成",
                "parameters": [
                    {
                        "description": "トーナメント作成情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateTournamentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "作成成功",
                        "schema": {
                            "$ref": "#/definitions/handler.TournamentResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "競合エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tournaments/active": {
            "get": {
                "description": "アクティブなトーナメントのみを取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "アクティブトーナメント取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.TournamentListResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tournaments/id/{id}": {
            "get": {
                "description": "指定されたIDのトーナメントを取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "ID別トーナメント取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "トーナメントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.TournamentResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tournaments/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのトーナメントを更新する（管理者のみ）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "トーナメント更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "トーナメントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "トーナメント更新情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateTournamentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/handler.TournamentResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのトーナメントを削除する（管理者のみ）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "トーナメント削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "トーナメントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "削除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "競合エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tournaments/{sport}": {
            "get": {
                "description": "指定されたスポーツのトーナメントを取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "スポーツ別トーナメント取得",
                "parameters": [
                    {
                        "enum": [
                            "volleyball",
                            "table_tennis",
                            "soccer"
                        ],
                        "type": "string",
                        "description": "スポーツ名",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.TournamentResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tournaments/{sport}/activate": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたスポーツのトーナメントをアクティブ状態にする（管理者のみ）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "トーナメントアクティブ化",
                "parameters": [
                    {
                        "enum": [
                            "volleyball",
                            "table_tennis",
                            "soccer"
                        ],
                        "type": "string",
                        "description": "スポーツ名",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "アクティブ化成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "競合エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tournaments/{sport}/bracket": {
            "get": {
                "description": "指定されたスポーツのトーナメントブラケットを取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "トーナメントブラケット取得",
                "parameters": [
                    {
                        "enum": [
                            "volleyball",
                            "table_tennis",
                            "soccer"
                        ],
                        "type": "string",
                        "description": "スポーツ名",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.BracketResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tournaments/{sport}/complete": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたスポーツのトーナメントを完了状態にする（管理者のみ）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "トーナメント完了",
                "parameters": [
                    {
                        "enum": [
                            "volleyball",
                            "table_tennis",
                            "soccer"
                        ],
                        "type": "string",
                        "description": "スポーツ名",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "完了成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "競合エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tournaments/{sport}/format": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたスポーツのトーナメント形式を切り替える（卓球の天候条件用、管理者のみ）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "トーナメント形式切り替え",
                "parameters": [
                    {
                        "enum": [
                            "table_tennis"
                        ],
                        "type": "string",
                        "description": "スポーツ名",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "形式切り替え情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SwitchFormatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "切り替え成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "競合エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tournaments/{sport}/progress": {
            "get": {
                "description": "指定されたスポーツのトーナメント進行状況を取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournaments"
                ],
                "summary": "トーナメント進行状況取得",
                "parameters": [
                    {
                        "enum": [
                            "volleyball",
                            "table_tennis",
                            "soccer"
                        ],
                        "type": "string",
                        "description": "スポーツ名",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.ProgressResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "未発見エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.Bracket": {
            "type": "object",
            "properties": {
                "format": {
                    "description": "トーナメント形式",
                    "type": "string",
                    "example": "standard"
                },
                "rounds": {
                    "description": "ラウンド配列",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Round"
                    }
                },
                "sport": {
                    "description": "スポーツ種目",
                    "type": "string",
                    "example": "volleyball"
                },
                "tournament_id": {
                    "description": "トーナメントID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.BracketResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "ブラケットデータ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.Bracket"
                        }
                    ]
                },
                "message": {
                    "description": "メッセージ",
                    "type": "string",
                    "example": "ブラケット情報を取得しました"
                },
                "success": {
                    "description": "成功フラグ",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.CreateMatchRequest": {
            "type": "object",
            "required": [
                "round",
                "scheduled_at",
                "team1",
                "team2",
                "tournament_id"
            ],
            "properties": {
                "round": {
                    "type": "string"
                },
                "scheduled_at": {
                    "type": "string"
                },
                "team1": {
                    "type": "string"
                },
                "team2": {
                    "type": "string"
                },
                "tournament_id": {
                    "type": "integer"
                }
            }
        },
        "handler.CreateTournamentRequest": {
            "type": "object",
            "required": [
                "format",
                "sport"
            ],
            "properties": {
                "format": {
                    "type": "string"
                },
                "sport": {
                    "type": "string"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "パスワード",
                    "type": "string",
                    "example": "password"
                },
                "username": {
                    "description": "ユーザー名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "handler.LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "メッセージ",
                    "type": "string",
                    "example": "ログインに成功しました"
                },
                "role": {
                    "description": "ユーザーロール",
                    "type": "string",
                    "example": "admin"
                },
                "success": {
                    "description": "成功フラグ",
                    "type": "boolean",
                    "example": true
                },
                "token": {
                    "description": "JWTトークン",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "username": {
                    "description": "ユーザー名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "handler.Match": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "description": "完了日時",
                    "type": "string",
                    "example": "2024-01-01T11:00:00Z"
                },
                "created_at": {
                    "description": "作成日時",
                    "type": "string",
                    "example": "2024-01-01T09:00:00Z"
                },
                "id": {
                    "description": "試合ID",
                    "type": "integer",
                    "example": 1
                },
                "round": {
                    "description": "ラウンド名",
                    "type": "string",
                    "example": "1st_round"
                },
                "scheduled_at": {
                    "description": "予定日時",
                    "type": "string",
                    "example": "2024-01-01T10:00:00Z"
                },
                "score1": {
                    "description": "チーム1のスコア",
                    "type": "integer",
                    "example": 3
                },
                "score2": {
                    "description": "チーム2のスコア",
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "description": "試合ステータス",
                    "type": "string",
                    "example": "pending"
                },
                "team1": {
                    "description": "チーム1",
                    "type": "string",
                    "example": "チームA"
                },
                "team2": {
                    "description": "チーム2",
                    "type": "string",
                    "example": "チームB"
                },
                "tournament_id": {
                    "description": "トーナメントID",
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "description": "更新日時",
                    "type": "string",
                    "example": "2024-01-01T11:00:00Z"
                },
                "winner": {
                    "description": "勝者",
                    "type": "string",
                    "example": "チームA"
                }
            }
        },
        "handler.MatchListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "件数",
                    "type": "integer",
                    "example": 10
                },
                "data": {
                    "description": "試合データ配列",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Match"
                    }
                },
                "message": {
                    "description": "メッセージ",
                    "type": "string",
                    "example": "試合一覧を取得しました"
                },
                "success": {
                    "description": "成功フラグ",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.MatchResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "試合データ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.Match"
                        }
                    ]
                },
                "message": {
                    "description": "メッセージ",
                    "type": "string",
                    "example": "試合情報を取得しました"
                },
                "success": {
                    "description": "成功フラグ",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.MatchStatistics": {
            "type": "object",
            "properties": {
                "average_score": {
                    "description": "平均スコア",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "completed_matches": {
                    "description": "完了試合数",
                    "type": "integer",
                    "example": 8
                },
                "completion_rate": {
                    "description": "完了率",
                    "type": "number",
                    "example": 0.5
                },
                "matches_by_round": {
                    "description": "ラウンド別試合数",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "pending_matches": {
                    "description": "未完了試合数",
                    "type": "integer",
                    "example": 8
                },
                "team_stats": {
                    "description": "チーム統計",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/handler.TeamStats"
                    }
                },
                "total_matches": {
                    "description": "総試合数",
                    "type": "integer",
                    "example": 16
                },
                "tournament_id": {
                    "description": "トーナメントID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.MatchStatisticsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "統計データ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.MatchStatistics"
                        }
                    ]
                },
                "message": {
                    "description": "メッセージ",
                    "type": "string",
                    "example": "試合統計を取得しました"
                },
                "success": {
                    "description": "成功フラグ",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.ProgressResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "進行状況データ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.TournamentProgress"
                        }
                    ]
                },
                "message": {
                    "description": "メッセージ",
                    "type": "string",
                    "example": "進行状況を取得しました"
                },
                "success": {
                    "description": "成功フラグ",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "description": "既存のJWTトークン",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "handler.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "メッセージ",
                    "type": "string",
                    "example": "トークンのリフレッシュに成功しました"
                },
                "success": {
                    "description": "成功フラグ",
                    "type": "boolean",
                    "example": true
                },
                "token": {
                    "description": "新しいJWTトークン",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "handler.Round": {
            "type": "object",
            "properties": {
                "matches": {
                    "description": "試合配列",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Match"
                    }
                },
                "name": {
                    "description": "ラウンド名",
                    "type": "string",
                    "example": "1st_round"
                }
            }
        },
        "handler.SubmitMatchResultRequest": {
            "type": "object",
            "required": [
                "score1",
                "score2",
                "winner"
            ],
            "properties": {
                "score1": {
                    "type": "integer",
                    "minimum": 0
                },
                "score2": {
                    "type": "integer",
                    "minimum": 0
                },
                "winner": {
                    "type": "string"
                }
            }
        },
        "handler.SwitchFormatRequest": {
            "type": "object",
            "required": [
                "format"
            ],
            "properties": {
                "format": {
                    "type": "string"
                }
            }
        },
        "handler.TeamStats": {
            "type": "object",
            "properties": {
                "average_score": {
                    "description": "平均得点",
                    "type": "number",
                    "example": 3
                },
                "losses": {
                    "description": "敗北数",
                    "type": "integer",
                    "example": 1
                },
                "matches_played": {
                    "description": "試合数",
                    "type": "integer",
                    "example": 4
                },
                "team_name": {
                    "description": "チーム名",
                    "type": "string",
                    "example": "チームA"
                },
                "total_score": {
                    "description": "総得点",
                    "type": "integer",
                    "example": 12
                },
                "wins": {
                    "description": "勝利数",
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "handler.Tournament": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "作成日時",
                    "type": "string",
                    "example": "2024-01-01T09:00:00Z"
                },
                "format": {
                    "description": "トーナメント形式",
                    "type": "string",
                    "example": "standard"
                },
                "id": {
                    "description": "トーナメントID",
                    "type": "integer",
                    "example": 1
                },
                "sport": {
                    "description": "スポーツ種目",
                    "type": "string",
                    "example": "volleyball"
                },
                "status": {
                    "description": "ステータス",
                    "type": "string",
                    "example": "active"
                },
                "updated_at": {
                    "description": "更新日時",
                    "type": "string",
                    "example": "2024-01-01T11:00:00Z"
                }
            }
        },
        "handler.TournamentListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "件数",
                    "type": "integer",
                    "example": 3
                },
                "data": {
                    "description": "トーナメントデータ配列",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Tournament"
                    }
                },
                "message": {
                    "description": "メッセージ",
                    "type": "string",
                    "example": "トーナメント一覧を取得しました"
                },
                "success": {
                    "description": "成功フラグ",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.TournamentProgress": {
            "type": "object",
            "properties": {
                "completed_matches": {
                    "description": "完了試合数",
                    "type": "integer",
                    "example": 8
                },
                "current_round": {
                    "description": "現在のラウンド",
                    "type": "string",
                    "example": "quarterfinal"
                },
                "format": {
                    "description": "トーナメント形式",
                    "type": "string",
                    "example": "standard"
                },
                "pending_matches": {
                    "description": "未完了試合数",
                    "type": "integer",
                    "example": 8
                },
                "progress_percent": {
                    "description": "進行率",
                    "type": "number",
                    "example": 50
                },
                "sport": {
                    "description": "スポーツ種目",
                    "type": "string",
                    "example": "volleyball"
                },
                "status": {
                    "description": "ステータス",
                    "type": "string",
                    "example": "active"
                },
                "total_matches": {
                    "description": "総試合数",
                    "type": "integer",
                    "example": 16
                },
                "tournament_id": {
                    "description": "トーナメントID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.TournamentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "トーナメントデータ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.Tournament"
                        }
                    ]
                },
                "message": {
                    "description": "メッセージ",
                    "type": "string",
                    "example": "トーナメント情報を取得しました"
                },
                "success": {
                    "description": "成功フラグ",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.UpdateMatchRequest": {
            "type": "object",
            "properties": {
                "round": {
                    "type": "string"
                },
                "scheduled_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "team1": {
                    "type": "string"
                },
                "team2": {
                    "type": "string"
                }
            }
        },
        "handler.UpdateTournamentRequest": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
